logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  port: 9090

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 2
      maximum-idle: 1
      pool-name: data-source
    url: jdbc:mysql://localhost:3306/expense_planner_db_uat?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    password: anshuSoft
    username: root
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true



